spring:
  application:
    name: MovieHiveBot

  datasource:
    url: jdbc:postgresql://dpg-cvt8unre5dus73a4i4lg-a.frankfurt-postgres.render.com:5432/moviehive_db
    username: moviehive_db_user
    password: byelYFTaloSKCDRl6G6j8OcLGz1Tai6W

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

bot:
  token: 8118155666:AAGD_OrrPsH0WyLyuF8MVzaD6VBobGzj6Bk
  name: MovieHiveBot