spring:
  application:
    name: MovieHiveBot

  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require
    username: postgres.otribfsjckdzcdfzuwgg
    password: MovieHiveDatabase
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

bot:
  token: 8118155666:AAGD_OrrPsH0WyLyuF8MVzaD6VBobGzj6Bk
  name: MovieHiveBot