spring:
  application:
    name: MovieHiveBot

  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.otribfsjckdzcdfzuwgg
    password: MovieHiveDatabase
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

bot:
  name: MovieHiveBot
  token: 8118155666:AAGD_OrrPsH0WyLyuF8MVzaD6VBobGzj6Bk
  webhook-path: /webhook/update
  webhook-url: https://comparative-calli-pdpteam-091286b8.koyeb.app/webhook/update
