spring:
  application:
    name: MovieHiveBot

  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.otribfsjckdzcdfzuwgg
    password: MovieHiveDatabase
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect

bot:
  name: MovieHiveBot
  token: 8118155666:AAFB2Kab2M55hgpCWIw--ksOZzj9zol8T44
  webhook-path: /webhook/update
  webhook-url: https://api.telegram.org/bot8118155666:AAFB2Kab2M55hgpCWIw--ksOZzj9zol8T44/setWebhook?url=https://youngest-lindie-pdpteam-e0ae510c.koyeb.app/webhook/update&secret_token=MovieHiveSecret123

